plantilla.ps: plantilla.ms
	groff plantilla.ms -p -ms > plantilla.ps
sya.ps: sya.ms
	groff sya.ms -p -ms > sya.ps
partesLogicasCompilador.ps: partesLogicasCompilador.ms
	groff partesLogicasCompilador.ms -p -ms > partesLogicasCompilador.ps
